"""Post-trace IR optimizations.

These passes run on the traced Statement list before emission to PTX.
They are semantics-preserving transformations that clean up the IR
produced by DSL sugar (operator overloading, RegArray.__setitem__, etc.)
to produce PTX identical to hand-written ptx.inst.* calls.

Currently: copy propagation — removes unnecessary mov instructions
generated by RegArray.__setitem__ by renaming the source register to
the target throughout the chain.
"""

from __future__ import annotations

from pyptx.ir.nodes import (
    Instruction,
    RegisterOperand,
    AddressOperand,
    VectorOperand,
    NegatedOperand,
    PipeOperand,
    ParenthesizedOperand,
    Statement,
    RegDecl,
)


def copy_propagate(statements: list[Statement]) -> list[Statement]:
    """Remove trivial mov instructions by renaming registers.

    When RegArray.__setitem__ emits ``mov.bN %dst, %src``, this pass:
    1. Renames %src → %dst in ALL preceding instructions in the chain
    2. Removes the mov instruction
    3. Removes the .reg declaration for %src if it becomes unused

    This produces PTX identical to writing ``ptx.inst.*(dst, ...)``
    directly — no extra registers, no extra movs.
    """
    # Find mov.bN %dst, %src where both are named registers
    # These come from RegArray.__setitem__
    renames: dict[str, str] = {}  # src → dst
    mov_indices: set[int] = set()

    for i, stmt in enumerate(statements):
        if not isinstance(stmt, Instruction):
            continue
        if stmt.opcode != "mov":
            continue
        if len(stmt.operands) != 2:
            continue
        # Check it's mov.bN (not mov.u32 or mov.pred)
        if not any(m.startswith(".b") for m in stmt.modifiers):
            continue
        dst_op, src_op = stmt.operands
        if not isinstance(dst_op, RegisterOperand) or not isinstance(src_op, RegisterOperand):
            continue
        dst_name = dst_op.name
        src_name = src_op.name
        if dst_name == src_name:
            continue
        # Only rename if src is a "fresh" temp from operator overloading.
        # Fresh temps are scalar regs (declared individually) that are
        # defined exactly once (by the operator) and used exactly once
        # (by this mov). Array regs (%r0..%rN from .reg .b32 %r<N>)
        # are NOT temps — they're part of the kernel's register allocation.
        # Detect fresh temps: they're declared as individual .reg (no count)
        # and have a high index or different type than the array.
        src_is_fresh = False
        for s in statements[:i]:
            if isinstance(s, RegDecl) and s.name == src_name and s.count is None:
                src_is_fresh = True
                break
        if not src_is_fresh:
            continue
        # Also verify src is defined exactly once and used exactly once (this mov)
        src_def_count = sum(1 for s in statements if isinstance(s, Instruction)
                           and s.operands and isinstance(s.operands[0], RegisterOperand)
                           and s.operands[0].name == src_name)
        src_use_count = sum(1 for s in statements if isinstance(s, Instruction)
                           and any(isinstance(op, RegisterOperand) and op.name == src_name
                                   for op in s.operands[1:]))
        if src_def_count != 1 or src_use_count != 1:
            continue
        renames[src_name] = dst_name
        mov_indices.add(i)

    if not renames:
        return statements

    # Apply renames: walk backward from each mov to rename src → dst
    # in all instructions that define or use src
    result: list[Statement] = []
    removed_regs: set[str] = set(renames.keys())

    for i, stmt in enumerate(statements):
        if i in mov_indices:
            continue  # remove the mov

        if isinstance(stmt, RegDecl):
            # Remove reg declarations for renamed-away registers
            if stmt.count is None and stmt.name in removed_regs:
                continue
            result.append(stmt)
            continue

        if isinstance(stmt, Instruction):
            # Rename operands
            new_ops = tuple(_rename_operand(op, renames) for op in stmt.operands)
            if new_ops != stmt.operands:
                from dataclasses import replace
                stmt = replace(stmt, operands=new_ops)
        result.append(stmt)

    return result


def _rename_operand(op, renames: dict[str, str]):
    """Rename register references in an operand."""
    if isinstance(op, RegisterOperand):
        new_name = renames.get(op.name, op.name)
        if new_name != op.name:
            return RegisterOperand(name=new_name)
        return op
    if isinstance(op, AddressOperand):
        new_base = renames.get(op.base, op.base)
        if new_base != op.base:
            return AddressOperand(base=new_base, offset=op.offset)
        return op
    if isinstance(op, VectorOperand):
        new_elems = tuple(_rename_operand(e, renames) for e in op.elements)
        if new_elems != op.elements:
            return VectorOperand(elements=new_elems)
        return op
    if isinstance(op, NegatedOperand):
        new_inner = _rename_operand(op.operand, renames)
        if new_inner is not op.operand:
            return NegatedOperand(operand=new_inner)
        return op
    if isinstance(op, PipeOperand):
        new_left = _rename_operand(op.left, renames)
        new_right = _rename_operand(op.right, renames)
        if new_left is not op.left or new_right is not op.right:
            return PipeOperand(left=new_left, right=new_right)
        return op
    if isinstance(op, ParenthesizedOperand):
        new_elems = tuple(_rename_operand(e, renames) for e in op.elements)
        if new_elems != op.elements:
            return ParenthesizedOperand(elements=new_elems)
        return op
    return op
